language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml tests/
  - php vendor/bin/phpcs --standard=PSR1,PSR2 --ignore=tests/autoload.php src tests

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v